### PR TITLE
Feature/integration test improvements

### PR DESCRIPTION
**Pull request by michaelbackes**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
read / write / update - fixes various issues found while integration testing

### CODE REVIEW

**Comment by piket** [comment]
In the `update` method, do we need to add a `collection.release()` before any operations? Also, it looks like we don't do anything with the `entities_to_keep` and `entities_to_delete` parameters. Do we have a plan to add in that support?

**Comment by michaelbackes** [comment]
> In the `update` method, do we need to add a `collection.release()` before any operations? Also, it looks like we don't do anything with the `entities_to_keep` and `entities_to_delete` parameters. Do we have a plan to add in that support?

I don't know if release is required. Would data need to be released every time we load new data into memory?

We should support `entities_to_keep` and `entities_to_delete`. Let's add a ticket to the backlog for that.

**Comment by piket** [comment]
> > In the `update` method, do we need to add a `collection.release()` before any operations? Also, it looks like we don't do anything with the `entities_to_keep` and `entities_to_delete` parameters. Do we have a plan to add in that support?
> 
> I don't know if release is required. Would data need to be released every time we load new data into memory?

I know that we need to release the data to make any structural changes (schema or indexes). For adding new data we should keep it loaded.

**Comment by michaelbackes** [comment]
> > > In the `update` method, do we need to add a `collection.release()` before any operations? Also, it looks like we don't do anything with the `entities_to_keep` and `entities_to_delete` parameters. Do we have a plan to add in that support?
> > 
> > 
> > I don't know if release is required. Would data need to be released every time we load new data into memory?
> 
> I know that we need to release the data to make any structural changes (schema or indexes). For adding new data we should keep it loaded.

ok, these changes are not supported yet (if ever) so I think we can keep it as is for now

**Review by piket — APPROVED** [review]

**Pull request merged**
